name: myst
channels:
  - conda-forge
  - defaults
dependencies:
  - git
  - python=3.7.*
  - jupyter
  - sphinx=2.4.4
  - pydata-sphinx-theme
  - sphinx_rtd_theme
  - ghp-import
  - numpy
  - matplotlib
  - scipy
  - pip
  - nbsphinx
  - pip:
    - git+https://github.com/executablebooks/MyST-NB.git
    - jupyter-cache[cli]
    - git+https://github.com/mwouts/jupytext.git
    
    
